Source        : System.Data.Entity
Method        : OpenStoreConnectionIf
Date        : 7:40:28 PM
Time        : 8/18/2016
Computer    : shekharp7
Error        : The underlying provider failed on Open.
Stack Trace    : at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
   at System.Data.EntityClient.EntityConnection.Open()
   at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predicate)
   at TrainingTracker.DAL.DataAccess.UserDal.ValidateUser(User userData) in d:\Projects\Traning-Tracker\TrainingTracker.DAL\DataAccess\UserDal.cs:line 34
^^-----------------------------------------------------^^
Source        : System.Data.Entity
Method        : OpenStoreConnectionIf
Date        : 7:40:33 PM
Time        : 8/18/2016
Computer    : shekharp7
Error        : The underlying provider failed on Open.
Stack Trace    : at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
   at System.Data.EntityClient.EntityConnection.Open()
   at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predicate)
   at TrainingTracker.DAL.DataAccess.UserDal.ValidateUser(User userData) in d:\Projects\Traning-Tracker\TrainingTracker.DAL\DataAccess\UserDal.cs:line 34
^^-----------------------------------------------------^^
Source        : System.Data.Entity
Method        : OpenStoreConnectionIf
Date        : 7:44:33 PM
Time        : 8/18/2016
Computer    : shekharp7
Error        : The underlying provider failed on Open.
Stack Trace    : at System.Data.EntityClient.EntityConnection.OpenStoreConnectionIf(Boolean openCondition, DbConnection storeConnectionToOpen, DbConnection originalConnection, String exceptionCode, String attemptedOperation, Boolean& closeStoreConnectionOnFailure)
   at System.Data.EntityClient.EntityConnection.Open()
   at System.Data.Objects.ObjectContext.EnsureConnection()
   at System.Data.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Objects.ObjectQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predicate)
   at TrainingTracker.DAL.DataAccess.UserDal.ValidateUser(User userData) in d:\Projects\Traning-Tracker\TrainingTracker.DAL\DataAccess\UserDal.cs:line 34
^^-----------------------------------------------------^^
